name: CI/CD

on:
    push:
        branches:
            - main

jobs:
  release:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:
        - uses: actions/checkout@v4
          with:
              # Pulls all commits (needed for semantic release to correctly version)
              # See https://github.com/semantic-release/semantic-release/issues/1526
              fetch-depth: "0"
              persist-credentials: false

        - name: Use Node.js 20
          uses: actions/setup-node@v4
          with:
              node-version: 20.x

        - run: npm install
        
        - name: Download release artifact
          uses: actions/download-artifact@v3
          with:
              name: release
              path: release

        - name: Release 🚀
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: npx semantic-release
          working-directory: ./release